#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bluetoothctl power on

#~/.dotfiles/scripts/monitors
~/.dotfiles/scripts/wallpaper/script
~/.dotfiles/polybar/start

picom --experimental-backends &

bspc config ignore_ewmh_focus true
bspc monitor DP-4 -d 一 二 三 四
bspc monitor HDMI-0 -d 五 六 七
bspc monitor DVI-D-0 -d 八 九 十

bspc config border_width         2
bspc config window_gap          15

bspc config focused_border_color \#a1cdf7
bspc config active_border_color  \#5e7991
bspc config normal_border_color  \#5e7991

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
