#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bluetoothctl power on
wmname LG3D &

df=~/.dotfiles

source $df/vars
$df/scripts/monitors
$df/scripts/wallpaper/script
$df/polybar/start

picom --experimental-backends &

bspc config ignore_ewmh_focus true
bspc monitor HDMI-2 -d 一 二 三 四
bspc monitor DP-1 -d 五 六 七
bspc monitor HDMI-1 -d 八 九 十

bspc wm --reorder-monitors HDMI-2 DP-1 HDMI-1

GAPS=$UI_GAPS
TOP_GAP=$(polybar --dump=border-size base)

bspc config border_width         2
bspc config window_gap          $GAPS
bspc config top_padding 	0 #-$TOP_GAP
bspc config right_padding 	0
bspc config bottom_padding 	0
bspc config left_padding 	0
bspc config top_monocle_padding $GAPS

bspc config focused_border_color $COLOR_PRIMARY
bspc config active_border_color  $COLOR_PRIMARY_INACTIVE
bspc config normal_border_color  $COLOR_PRIMARY_INACTIVE

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 'Google-chrome' desktop='五'
#bspc rule -a 'jetbrains-phpstorm' desktop='二'  
bspc rule -a DBeaver desktop='七'
bspc rule -a Mattermost desktop='八'
bspc rule -a Brave-browser desktop='十' 
bspc rule -a Thunderbird desktop='六'

$df/scripts/autostart &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
