#!/bin/bash

xrandr --output HDMI-2 --primary --mode 1920x1080 --rate 60
xrandr --output HDMI-3 --mode 1920x1080 --rate 60 --right-of HDMI-2
xrandr --output DP-2 --mode 1440x900 --rate 60 --left-of HDMI-2
