#!/bin/bash

xrandr --output HDMI-1 --mode 1920x1080 --rate 60
xrandr --output HDMI-2 --primary --mode 1920x1080 --rate 60 --right-of HDMI-1
xrandr --output DP-1 --mode 1920x1080 --rate 60 --right-of HDMI-2
