#!/bin/bash

xrandr --output DP-4 --primary --mode 2560x1440 --rate 165
xrandr --output HDMI-0 --mode 1920x1080 --rate 60 --right-of DP-4
xrandr --output DVI-D-0 --mode 1366x768 --rate 60 --left-of DP-4
